* Encoding: UTF-8.

FILTER BY outlier.

CROSSTABS
  /TABLES=strategy_2x2 BY group
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT 
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=strategy_4x2 BY group
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT 
  /COUNT ROUND CELL.
